version: '3.3'
services:
    main:
        restart: unless-stopped
        image: ghcr.io/angelesorganization/switchdate-backend:main
        # image: fastapi-local:latest
        ports:
            - 8002:8000
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_SERVER: db
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres

    db:
      image: postgres
      restart: always
      ports:
        - "5433:5432"
      environment:
        POSTGRES_PASSWORD: example